services:
  github-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-pipeline
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "50051:50051"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ORG=${GITHUB_ORG}
      - STORAGE_TYPE=${STORAGE_TYPE:-duckdb}
      - STORAGE_PATH=${STORAGE_PATH:-data/github_data.db}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT:-50051}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: run --full
    restart: unless-stopped
